<?

$LOCA["en"]["LONG_1"] = "The main supplier of raw materials for the construction of load-bearing structures of buildings and ships. Metal - the cheapest raw materials, but it takes more than the rest. For the production of the metal requires the least energy. More than mines, so they are deeper. On most planets, the metal is at greater depths in these deeper mines can produce more metals production increases. At the same time a large mines require more energy.";
$LOCA["en"]["LONG_106"] = "Espionage is designed to explore new and better sensors. The more developed the technology, the more information a player has on the events in their environment. The difference in the levels of espionage with the opponent plays a crucial role - the more investigated own spy technology, the more information is contained in the intelligence and the less chance of being detected. The more probes are sent, the more details about the enemy is going, but at the same time increasing the risk of being detected. Also espionage improves locating foreign fleets. This also important is the level of development of its own espionage. Starting from the second level of its development in an attack on you except to report on the attack, and also shows the total number of attacking ships. On the fourth level of recognized species attacking ships, as well as their overall strength, and the eighth - the exact number of each type of ship. For the Raiders, this technology is very important because it provides information on whether the victim has exposed the fleet and / or protection or not, so you should investigate it as soon as possible. Best of all - immediately after the study of small vehicles.";
$LOCA["en"]["LONG_108"] = "Computer technology is designed to increase the available computing power. As a result, the planet develop more productive and effective computer systems, increased computing power and speed of the flow of computational processes. With the increasing power of computers can simultaneously lead by an increasing number of fleets. Each level of the development of computer technology makes it possible to command a fleet of one. The more distributed fleet, the more you can make raids and thereby capture more raw materials. Naturally, this technology is useful and traders, as it allows them to simultaneously send more trade fleets. For this reason it is necessary to continuously develop computer technology throughout the game.";
$LOCA["en"]["LONG_109"] = "Weapons Technology deals mainly with the further development of available weapons systems. Special importance is given to ensure that the available supply of more energy and more accurately direct this energy. With this weapon system becomes more efficient, and the weapon causes more damage. Each level of weapons technology increases the power of weapons of military units by 10%. Weapons Technology is important for the competitive parts of the content. Therefore, it should be continuously developed throughout the game.";

$LOCA["en"]["LONG_124"] = "Expedition technology covers a variety of scanning technology and provides an opportunity to equip the ships of different classes of research module. It contains a database, a small mobile laboratory, and various biokletki and vessels for trial. For the safety of the ship in the study of dangerous objects research module is equipped with autonomous energy supply and energy field generator, which in extreme cases can surround the research module powerful energy field.";
$LOCA["en"]["LONG_203"] = "On board this ship has only a weak weapons and no serious technology... For this reason, they should never be run without an escort. Thanks to its highly developed large transport jet engine serves as a fast interplanetary deliverer of resources, it is also accompanied by fleets in the attacks on the enemy planet to capture as much resources.";
$LOCA["en"]["LONG_202"] = "Transports are about the same size as the fighters, but they do not have powerful engines and on-board armament for the sake of saving space. Small Cargo holds 5000 units of resources. Due to the low firepower small transports are often accompanied by other ships. When the pulse motor investigated before the 5th stage with a small transport increases base rate and it is equipped with this type of engine.";


// Language hack
$LOCA["en"]["NAME_124"] = "Expedition technology";
?>